export const QueuedJobStatus = {
    "NEW": "New",
    "QUEUED": "Queued",
    "PROCESSING": "Processing",
    "FINISHED": "Finished",
    "FAILED": "Failed"
};

export const EntityType = {
    "COMPANY": "Company",
    "INDIVIDUAL": "Individual"
};

export const Currency = {
    "AED": "AED",
    "AFN": "AFN",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BHD": "BHD",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BTN": "BTN",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CAD": "CAD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "CNY": "CNY",
    "COP": "COP",
    "CRC": "CRC",
    "CUP": "CUP",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DKK": "DKK",
    "DOP": "DOP",
    "DZD": "DZD",
    "EGP": "EGP",
    "ERN": "ERN",
    "ETB": "ETB",
    "EUR": "EUR",
    "FJD": "FJD",
    "FKP": "FKP",
    "GBP": "GBP",
    "GEL": "GEL",
    "GHS": "GHS",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "INR": "INR",
    "IQD": "IQD",
    "IRR": "IRR",
    "ISK": "ISK",
    "JMD": "JMD",
    "JOD": "JOD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KPW": "KPW",
    "KRW": "KRW",
    "KWD": "KWD",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LBP": "LBP",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "LYD": "LYD",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRU": "MRU",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "OMR": "OMR",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PKR": "PKR",
    "PLN": "PLN",
    "PYG": "PYG",
    "QAR": "QAR",
    "RON": "RON",
    "RSD": "RSD",
    "RUB": "RUB",
    "RWF": "RWF",
    "SAR": "SAR",
    "SBD": "SBD",
    "SCR": "SCR",
    "SDG": "SDG",
    "SEK": "SEK",
    "SGD": "SGD",
    "SHP": "SHP",
    "SLE": "SLE",
    "SOS": "SOS",
    "SRD": "SRD",
    "SSP": "SSP",
    "STN": "STN",
    "SYP": "SYP",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TMT": "TMT",
    "TND": "TND",
    "TOP": "TOP",
    "TRY": "TRY",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "USD": "USD",
    "UYU": "UYU",
    "UZS": "UZS",
    "VES": "VES",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XCG": "XCG",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "ZWG": "ZWG"
};

export const InvoiceItemUnit = {
    "HOUR": "Hour",
    "DAY": "Day",
    "WEEK": "Week",
    "MONTH": "Month",
    "YEAR": "Year",
    "PIECE": "Piece",
    "SET": "Set",
    "KIT": "Kit",
    "BOX": "Box",
    "PACK": "Pack",
    "DOZEN": "Dozen",
    "KILOGRAM": "Kilogram",
    "GRAM": "Gram",
    "TONNE": "Tonne",
    "METER": "Meter",
    "CENTIMETER": "Centimeter",
    "SQUARE_METER": "Square Meter",
    "LITER": "Liter",
    "SERVICE": "Service",
    "FLAT_RATE": "Flat Rate",
    "PROJECT": "Project"
};

export const InvoiceStatus = {
    "DRAFT": "Draft",
    "SENT": "Sent",
    "PAID": "Paid",
    "OVERDUE": "Overdue"
};

export const InvoiceType = {
    "INCOME": "Income",
    "EXPENSE": "Expense"
};

export const InvoiceTemplate = {
    "STANDARD": "Standard",
    "MODERN": "Modern",
    "MINIMALIST": "Minimalist",
    "CLEAN": "Clean",
    "PROFESSIONAL": "Professional",
    "ARCHITECTURAL": "Architectural",
    "HORIZONTAL": "Horizontal"
};

